Fix required parameters after optional parameters in method signatures
zendtech/IbmiToolkit pull request #156
Opened 2021-04-15 07:10 UTC by wjonkerhulst

Related to https://github.com/zendtech/IbmiToolkit/issues/154

2021-04-16 15:55 UTC, NattyNarwhal commented
I thought I got most of these already, glad someone's catching the others.

FWIW, we internally do calls every Friday afternoons for PR review/Toolkit direction, so it should it should be reviewed/merged then - and if you didn't write this, we'd have looked at your original issue. It looks good at first glance anyways.

2021-04-16 19:01 UTC, alanseiden requested changes
Thank you for this PR. Please see requested changes inline.

2021-04-16 19:01 UTC, alanseiden commented on ToolkitApi/CW/Int16Param.php
> -    public function __construct($io, $comment, $varName='', $value, $dimension=0, $by='', $isArray = false, $labelSetLen=null)
Instead of making $varName mandatory, please make $value optional, similar to what was done in this commit: https://github.com/zendtech/IbmiToolkit/commit/bb9831b20b847a430e10e3f2f27a47e3fd859c5f
Same for other the other methods referenced in your PR.

2021-04-20 15:35 UTC, alanseiden commented
@wjonkerhulst Thank you. We will review your updates on Friday, if not before.

2021-04-23 18:37 UTC, NattyNarwhal approved these changes

2021-04-23 18:37 UTC, merged